addr-raft = "node2:8081"
addr-client = "node2:8082"
dir-data = "/tmp/tinykv"

[raft]
max-entry-bytes = "200MB"

[prophet]
name = "node2"
rpc-addr = "node2:8083"
prophet-node = true

[prophet.embed-etcd]
join = "http://node0:8085"
client-urls = "http://0.0.0.0:8084"
advertise-client-urls = "http://node2:8084"
peer-urls = "http://0.0.0.0:8085"
advertise-peer-urls = "http://node2:8085"

[prophet.replication]
max-replicas = 3