addr-raft = "node1:8081"
addr-client = "node1:8082"
dir-data = "/tmp/tinykv"

[replication]
shard-capacity-bytes = "96MB"

[raft]
max-entry-bytes = "10MB"

[prophet]
name = "node1"
rpc-addr = "node1:8083"
storage-node = true

[prophet.embed-etcd]
join = "http://node0:8085"
client-urls = "http://0.0.0.0:8084"
advertise-client-urls = "http://node1:8084"
peer-urls = "http://0.0.0.0:8085"
advertise-peer-urls = "http://node1:8085"

[prophet.replication]
max-replicas = 3